baseURL = "https://fckner.github.io"
languageCode = "hu"
title = "o1g"
theme = "strange-case"
copyright = "Public Domain"
canonifyurls = true
paginate = 500

[params]
    colorScheme = "scheme-darkbrown"
    DateFormat = "2006.01.02"
    description = "Fuck NER"
    sidebarDescription = ""
    sidebarFreeText = ""

[[menu.main]]
	name = "Főnök"
	post = "<span class='glyphicon glyphicon-king'></span>"
	url = "/miattuk-szar-ez-az-orszag/orban-viktor"
	weight = 10

[[menu.main]]
	name = "Oligarchák"
	post = "<span class='glyphicon glyphicon-queen'></span>"
	url = "/tags/oligarcha"
	weight = 20

[[menu.main]]
	name = "Főkáderek"
	post = "<span class='glyphicon glyphicon-tower'></span>"
	url = "/tags/főkáder"
	weight = 30

[[menu.main]]
	name = "Beszélő fejek"
	post = "<span class='glyphicon glyphicon-bishop'></span>"
	url = "/tags/beszélő-fej"
	weight = 40

[[menu.main]]
	name = "Helytartók"
	post = "<span class='glyphicon glyphicon-knight'></span>"
	url = "/tags/helytartó"
	weight = 50

[[menu.main]]
	name = "Mítoszok"
	post = "<span class='glyphicon glyphicon-picture'></span>"
	url = "/tags/mítosz"
	weight = 60

[[menu.main]]
	name = "Autokrácia"
	post = "<span class='glyphicon glyphicon-eye-open'></span>"
	url = "/tags/autokrácia"
	weight = 70

[[menu.main]]
	name = "Kleptokrácia"
	post = "<span class='glyphicon glyphicon-euro'></span>"
	url = "/tags/kleptokrácia"
	weight = 80

[[menu.main]]
	name = "Maffiaállam"
	post = "<span class='glyphicon glyphicon-piggy-bank'></span>"
	url = "/tags/maffiaállam"
	weight = 90

[[menu.main]]
	name = "Aljasságok"
	post = "<span class='glyphicon glyphicon-screenshot'></span>"
	url = "/tags/aljasság"
	weight = 100

[[menu.main]]
	name = "Írj te is!"
	post = "<span class='glyphicon glyphicon-bullhorn'></span>"
	url = "https://github.com/fckner/fckner"
	weight = 200
